// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzwGqXNpcUrrQwW9Vlpap_pXRBgW88gWo',
    appId: '1:5740484175:android:7cefd3cd37b927e8237c3a',
    messagingSenderId: '5740484175',
    projectId: 'tabs-b303e',
    storageBucket: 'tabs-b303e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEvRtQKg7UP-0p5Ln2P51TZ5gQA3ViSuY',
    appId: '1:5740484175:ios:b59900eb5440a69f237c3a',
    messagingSenderId: '5740484175',
    projectId: 'tabs-b303e',
    storageBucket: 'tabs-b303e.firebasestorage.app',
    iosBundleId: 'com.app.tabs',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzwGqXNpcUrrQwW9Vlpap_pXRBgW88gWo',
    appId: '1:5740484175:web:b59900eb5440a69f237c3a',
    messagingSenderId: '5740484175',
    projectId: 'tabs-b303e',
    storageBucket: 'tabs-b303e.firebasestorage.app',
    authDomain: 'tabs-b303e.firebaseapp.com',
  );
}